### ISSUE TITLE
Missing Database function on SetTheme command

### ISSUE THREAD

**Issue by klerikdust** [klerikdust/anniediscord#240]
**Describe the bug**
.setTheme() function missing in the database lib file

**To Reproduce**
1. Make sure the user has Donator/Server Booster Privilege
2. Type `>setTheme` or `>theme` in the command-enabled channel
3. See error

**Expected behavior**
Executing the theme switch for the user

**Comment by BaitGod01** [comment]
In order to fix this, we need to know where their theme setting is saved. As in what DB table and under what column.

**Comment by klerikdust** [comment]
> In order to fix this, we need to know where their theme setting is saved. As in what DB table and under what column.

@BaitGod01 Theme is stored as an a regular item in user inventory, then the "in_use" column decides which theme is currently being set.
