### ISSUE TITLE
[Feature] Quick Start guide

### ISSUE THREAD

**Issue by Moore2021** [klerikdust/anniediscord#252]
**Is your feature request related to a problem? Please describe.**
There are a lot of settings for a new server and may seem like a lot.

**Describe the solution you'd like**
Create a command that walks through a new server on what settings they should set up.

**Describe alternatives you've considered**
Have a dedicated channel on the support server that acts as a guide/FAQ.

**Additional context**
the settings should be important ones that are used to make a module work.

**Comment by klerikdust** [comment]
Implementing both solutions would great i guess.

**Comment by klerikdust** [comment]
We can try writing down the general FAQ in the support server first, then convert them into an actual quick-guide command/message.

**Comment by Moore2021** [comment]
Imma close this for now as we have started this and can continue to add when needed.
