### ISSUE TITLE
[BUG] Can't change guild bio in a new server

### ISSUE THREAD

**Issue by klerikdust** [klerikdust/anniediscord#257]
**Describe the bug**
I was inviting Annie to a new server, and noticed that I can't change the guild bio. It displays the "lang" error instead.
Edit: this happened for the first time, but it working fine on second try.

**To Reproduce**
1. Use >setGuildBio in command-enabled channel
2. See error

**Expected behavior**
I'm not sure how the command actually would response since I never use it before, but I assume it should give me the prompt to type the new guild bio.

**Screenshots**

**Comment by Moore2021** [comment]
What's the bug? like does it still bug?
Usage is >setguildbio <bio>
no prompt was built in.
