### ISSUE TITLE
[BUG] Wrong reference in guildMemberUpdate.js

### ISSUE THREAD

**Issue by klerikdust** [klerikdust/anniediscord#278]
**Describe the bug**
guildMemberUpdate.js still using the old ref for fetching user.

**To Reproduce**
1. Go to `./src/events/guildMemberUpdate.js`
2. Scroll down to line `17`
4. Waits until new member joined the guild
5. See error

**Expected behavior**
Shouldn't throw an error when there's new member joining (this only triggered to production mode).

**Screenshots**
![image](https://user-images.githubusercontent.com/42025692/90375064-9fe10400-e09e-11ea-8ebf-8bd409eaa6de.png)

**Comment by Moore2021** [comment]
I'm pretty sure my most recent pr fixes this one
