### ISSUE TITLE
[BUG] DiscordAPI Missing Permission

### ISSUE THREAD

**Issue by klerikdust** [klerikdust/anniediscord#279]
**Describe the bug**
Not sure where is this coming from, but it keeps throwing a `DiscordAPIError: Missing Permissions` error at certain interval time.

**To Reproduce**
1. Starts the bot in production mode
2. Type `pm2 log` in the terminal
3. See error

**Expected behavior**
The current permissions integers should be logically correct. Or perhaps there's one of the features that requires admin privilege?

**Screenshots**
![image](https://user-images.githubusercontent.com/42025692/90375955-e7b45b00-e09f-11ea-96ba-27ef1dca8387.png)

**Comment by Moore2021** [comment]
this can be caused by a number of things that could be out of our reach
[Permissions](https://discordjs.guide/popular-topics/permissions-extended.html#limitations-and-oddities)

**Comment by klerikdust** [comment]
oh well.. i guess this bug gonna stay for a while,
