### ISSUE TITLE
[BUG] Wrong ref in guildMemberUpdate.js

### ISSUE THREAD

**Issue by klerikdust** [klerikdust/anniediscord#285]
**Describe the bug**
The error seems to be occured everytime user's roles got changed.

**To Reproduce**
1. Go to a guild where Annie is being hosted in
2. Assign/unassign roles from one of the guild member
3. See error (if you are running in development, make sure to put the `guildMemberUpdate` variable call to the outside of production scope in `./src/controllers/events`)

**Expected behavior**
Should not log an error every time user is getting roles change.

**Screenshots**
![image](https://user-images.githubusercontent.com/42025692/90641789-d2842b80-e25b-11ea-9f16-d48902942fe3.png)

**Comment by Moore2021** [comment]
didn't I fix this?

**Comment by klerikdust** [comment]
> didn't I fix this?
@Moore2021 I'm not sure, it still occurring in the production server.
